// 'use client'
import { Inter } from 'next/font/google';
import '../app/globals.css';
import Footer from './footer/footer';
import Navbar from './navbar/Navbar';
import { dark } from '@clerk/themes';
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
  SignInComponent
} from '@clerk/nextjs';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  console.log("at here")
  return (
    <ClerkProvider
    appearance={{
      baseTheme: dark,
    }} >
    <html lang="en">
      <body className={inter.className}>
        <SignedOut>
          <SignInComponent />
        </SignedOut>
        <SignedIn>
          <Navbar />
          <UserButton />
          {children}
          <Footer />
        </SignedIn>
      </body>
    </html>
    // </ClerkProvider>
  );
}
